"""Central enum definitions for the domain.

Keeping these in one module avoids circular imports and gives the UI a single
source of truth for labels / colours.
"""


class Role:
    STUDENT = "STUDENT"
    RECRUITER = "RECRUITER"
    ADMIN = "ADMIN"

    ALL = (STUDENT, RECRUITER, ADMIN)


class RecruiterApprovalStatus:
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

    ALL = (PENDING, APPROVED, REJECTED)


class OpportunityType:
    INTERNSHIP = "INTERNSHIP"
    FULL_TIME = "FULL_TIME"

    ALL = (INTERNSHIP, FULL_TIME)


class OpportunityStatus:
    DRAFT = "DRAFT"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"      # approved by admin → visible to students
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"

    ALL = (DRAFT, PENDING_REVIEW, APPROVED, REJECTED, CLOSED)
    SUBMITTABLE = (DRAFT, REJECTED)  # can be sent for (re)review
    VISIBLE_TO_STUDENTS = (APPROVED, CLOSED)


class ApplicationStatus:
    APPLIED = "APPLIED"
    UNDER_REVIEW = "UNDER_REVIEW"
    SHORTLISTED = "SHORTLISTED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    SELECTED = "SELECTED"
    REJECTED = "REJECTED"

    ALL = (APPLIED, UNDER_REVIEW, SHORTLISTED, INTERVIEW_SCHEDULED, SELECTED, REJECTED)
    TERMINAL = (SELECTED, REJECTED)

    # Allowed transitions for recruiters (state machine — validated server side).
    # INTERVIEW_SCHEDULED is deliberately NOT recruiter-selectable here: only the
    # interview scheduling transaction may move an application into that state.
    TRANSITIONS = {
        APPLIED: {UNDER_REVIEW, SHORTLISTED, REJECTED},
        UNDER_REVIEW: {SHORTLISTED, REJECTED},
        SHORTLISTED: {REJECTED},
        INTERVIEW_SCHEDULED: {SELECTED, REJECTED},
        SELECTED: set(),
        REJECTED: set(),
    }

    # Human-readable labels
    LABELS = {
        APPLIED: "Applied",
        UNDER_REVIEW: "Under Review",
        SHORTLISTED: "Shortlisted",
        INTERVIEW_SCHEDULED: "Interview Scheduled",
        SELECTED: "Selected",
        REJECTED: "Rejected",
    }


class InterviewStatus:
    SCHEDULED = "SCHEDULED"
    UPDATED = "UPDATED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"

    ALL = (SCHEDULED, UPDATED, CANCELLED, COMPLETED)


class NotificationType:
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    APPLICATION_STATUS_CHANGED = "APPLICATION_STATUS_CHANGED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_UPDATED = "INTERVIEW_UPDATED"
    INTERVIEW_CANCELLED = "INTERVIEW_CANCELLED"
    RECRUITER_APPROVED = "RECRUITER_APPROVED"
    RECRUITER_REJECTED = "RECRUITER_REJECTED"
    OPPORTUNITY_APPROVED = "OPPORTUNITY_APPROVED"
    OPPORTUNITY_REJECTED = "OPPORTUNITY_REJECTED"
    NEW_APPLICATION = "NEW_APPLICATION"
    RECRUITER_PENDING = "RECRUITER_PENDING"

    ALL = (
        EMAIL_VERIFICATION,
        APPLICATION_SUBMITTED,
        APPLICATION_STATUS_CHANGED,
        INTERVIEW_SCHEDULED,
        INTERVIEW_UPDATED,
        INTERVIEW_CANCELLED,
        RECRUITER_APPROVED,
        RECRUITER_REJECTED,
        OPPORTUNITY_APPROVED,
        OPPORTUNITY_REJECTED,
        NEW_APPLICATION,
        RECRUITER_PENDING,
    )


class AuditAction:
    ADMIN_APPROVED_RECRUITER = "ADMIN_APPROVED_RECRUITER"
    ADMIN_REJECTED_RECRUITER = "ADMIN_REJECTED_RECRUITER"
    ADMIN_APPROVED_OPPORTUNITY = "ADMIN_APPROVED_OPPORTUNITY"
    ADMIN_REJECTED_OPPORTUNITY = "ADMIN_REJECTED_OPPORTUNITY"
    ADMIN_SUSPENDED_USER = "ADMIN_SUSPENDED_USER"
    ADMIN_REACTIVATED_USER = "ADMIN_REACTIVATED_USER"
    ADMIN_CLOSED_OPPORTUNITY = "ADMIN_CLOSED_OPPORTUNITY"
