"""add weekly_digest_enabled to recruiter_profiles

Revision ID: 5cb6c764c72e
Revises: 54af6c188785
Create Date: 2026-08-21 23:13:36.799193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb6c764c72e'
down_revision = '54af6c188785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiter_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_digest_enabled', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiter_profiles', schema=None) as batch_op:
        batch_op.drop_column('weekly_digest_enabled')

    # ### end Alembic commands ###
